name: Keep alive cron job
on:
  schedule:
    - cron: '*/5 * * * *' # https://crontab.guru/#0_12_*_*_*
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          curl --request POST \
          --url '${{ secrets.SITE_URL }}/api/keep-alive' \
          --header 'x-keep-alive-api-secret: ${{ secrets.KEEP_ALIVE_API_SECRET }}'